workflows:
  hello-world:
    name: Hello world workflow
    max_build_duration: 100
    environment:
      vars:
        GOOGLE_PLAY_TRACK: "beta"
        flutter: stable
        xcode: latest
        cocoapods: 1.9.1
        node: 12.14.0
        npm: 6.13.7
        ndk: r21d
        java: 1.8
        ruby: 2.7.2

    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules

    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get

      - name: Build ios
        script: flutter build ios --release

    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - mohammed@nevercode.io
          - kevin@nevercode.io

    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
        - pattern: develop
          include: false
        - pattern: feature-1
          include: true
        - pattern: main
          include: true
