workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          echo "Updating Homebrew..."
          brew update || true
          echo "Installing CocoaPods..."
          brew install cocoapods || brew upgrade cocoapods
          echo "Running pod install..."
          pod install
      - name: Build the app
        script: |
          echo "Building the app..."
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator -configuration Release build
    artifacts:
      - build/ios/Release-iphonesimulator/*.app
