// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9StRFG4EnBAna8HB-aOkLGyIprZ1myU',
    appId: '1:714314647333:web:822de5dea12386a2cebccc',
    messagingSenderId: '714314647333',
    projectId: 'group10-appdev',
    authDomain: 'group10-appdev.firebaseapp.com',
    databaseURL: 'https://group10-appdev-default-rtdb.firebaseio.com',
    storageBucket: 'group10-appdev.appspot.com',
    measurementId: 'G-KK4X5DXG4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUZcDuHMdchrfDSGHnEI1iKOxNzzXy4Lg',
    appId: '1:714314647333:android:a9a071307cf91f5fcebccc',
    messagingSenderId: '714314647333',
    projectId: 'group10-appdev',
    databaseURL: 'https://group10-appdev-default-rtdb.firebaseio.com',
    storageBucket: 'group10-appdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9gIHbCj9_bErSM0xhf3VthKTrrD8Xm8',
    appId: '1:714314647333:ios:fff4006b7a7f0a13cebccc',
    messagingSenderId: '714314647333',
    projectId: 'group10-appdev',
    databaseURL: 'https://group10-appdev-default-rtdb.firebaseio.com',
    storageBucket: 'group10-appdev.appspot.com',
    iosBundleId: 'com.example.agwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU9gIHbCj9_bErSM0xhf3VthKTrrD8Xm8',
    appId: '1:714314647333:ios:b6e3309f7b0395b0cebccc',
    messagingSenderId: '714314647333',
    projectId: 'group10-appdev',
    databaseURL: 'https://group10-appdev-default-rtdb.firebaseio.com',
    storageBucket: 'group10-appdev.appspot.com',
    iosBundleId: 'com.example.agwa.RunnerTests',
  );
}
